INSERT INTO CATEGORY (description) VALUES ('nsfw')
INSERT INTO CATEGORY (description) VALUES ('dark')
INSERT INTO CATEGORY (description) VALUES ('sport')
INSERT INTO CATEGORY (description) VALUES ('misc')
INSERT INTO CATEGORY (description) VALUES ('insult')
INSERT INTO CATEGORY (description) VALUES ('politics')
INSERT INTO JOKE (JOKETEXT,CATEGORY_ID) VALUES ('Why don''t witches wear undies? To get a better grip on their brooms.',1)
INSERT INTO JOKE (JOKETEXT,CATEGORY_ID) VALUES ('This was a really, really big year for me. I got to go home for Thanksgiving and sit at the adults'' table. That''s ''cause, you know, somebody had to die for me to move up a plate.',2)
INSERT INTO JOKE (JOKETEXT,CATEGORY_ID) VALUES ('Why the collossi fell? Because it was imbalanced.',3)
INSERT INTO JOKE (JOKETEXT,CATEGORY_ID) VALUES ('You''re so stupid that you had to call 411 to get the number for 911.',4)
INSERT INTO JOKE (JOKETEXT,CATEGORY_ID) VALUES ('I''m trying to see things from your point of view, but I can''t get my head that far up my ass.',5)
INSERT INTO JOKE (JOKETEXT,CATEGORY_ID) VALUES ('If minorities have the race card and women have the gender card, what do rednecks have? The Trump Card',6)
INSERT INTO VOTE (VOTE_VALUE,JOKE_ID) VALUES (5,2)
INSERT INTO VOTE (VOTE_VALUE,JOKE_ID) VALUES (2,2)
INSERT INTO VOTE (VOTE_VALUE,JOKE_ID) VALUES (3,2)
INSERT INTO VOTE (VOTE_VALUE,JOKE_ID) VALUES (4,2)
INSERT INTO REPORT (REASON,JOKE_ID) VALUES ('Ofredande av andre',4)